### ISSUE TITLE
VCS tests failed on Fedora 24

### ISSUE THREAD

**Issue by sagitter** [Cantera/cantera#351]
Hi.

We are near to complete the RPM packaging of Cantera. There are some tests failed:

```
* Running test 'VCS-NaCl'...
Comparing 'good_out.txt' with 'test_output.txt'
Found differences between /home/sagitter/rpmbuild/BUILD/cantera-d4ddabc76c2bdfd54d61f76de6bfe477912325eb/test_problems/VCSnonideal/NaCl_equil/good_out.txt and /home/sagitter/rpmbuild/BUILD/cantera-d4ddabc76c2bdfd54d61f76de6bfe477912325eb/test_problems/VCSnonideal/NaCl_equil/test_output.txt:
>>>
--- 

+++ 

@@ -276,16 +276,16 @@



 Counters:         Iterations          Time (seconds)
-    vcs_basopt:       2                 NA
-    vcs_TP:          18                 NA
+    vcs_basopt:       2             2.70000E-05
+    vcs_TP:          18             5.26100E-03
 --------------------------------------------------------------------------------
 --------------------------------------------------------------------------------

 TCounters:   Num_Calls   Total_Its       Total_Time (seconds)
-    vcs_basopt:       2          2             NA
-    vcs_TP:           1         18             NA
-    vcs_inest:        1                        NA
-    vcs_TotalTime:                             NA
+    vcs_basopt:       2          2         2.70000E-05
+    vcs_TP:           1         18         5.26100E-03
+    vcs_inest:        1                    1.55000E-04
+    vcs_TotalTime:                         6.23300E-03

  Results from vcs:

<<<
FAILED
g++ -o test_problems/VCSnonideal/LatticeSolid_LiSi/latsol.o -c -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic --std=c++14 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -pthread -DNDEBUG -DNDEBUG -Iinclude -Isrc -Itest_problems/shared -I/usr/include/eigen3 -I/usr/include test_problems/VCSnonideal/LatticeSolid_LiSi/latsol.cpp
g++ -o test_problems/VCSnonideal/LatticeSolid_LiSi/latsol -pthread -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld test_problems/VCSnonideal/LatticeSolid_LiSi/latsol.o -Lbuild/lib -lcantera -lsundials_cvodes -lsundials_ida -lsundials_nvecserial -lfmt
* Running test 'VCS-LiSi'...
Comparing 'output_blessed.txt' with 'output_output.txt'
Found differences between /home/sagitter/rpmbuild/BUILD/cantera-d4ddabc76c2bdfd54d61f76de6bfe477912325eb/test_problems/VCSnonideal/LatticeSolid_LiSi/output_blessed.txt and /home/sagitter/rpmbuild/BUILD/cantera-d4ddabc76c2bdfd54d61f76de6bfe477912325eb/test_problems/VCSnonideal/LatticeSolid_LiSi/output_output.txt:
>>>
--- 

+++ 

@@ -210,16 +210,16 @@



 Counters:         Iterations          Time (seconds)
-    vcs_basopt:       1                 NA
-    vcs_TP:           3                 NA
+    vcs_basopt:       1             1.70000E-05
+    vcs_TP:           3             2.07000E-04
 --------------------------------------------------------------------------------
 --------------------------------------------------------------------------------

 TCounters:   Num_Calls   Total_Its       Total_Time (seconds)
-    vcs_basopt:       1          1             NA
-    vcs_TP:           1          3             NA
-    vcs_inest:        0                        NA
-    vcs_TotalTime:                             NA
+    vcs_basopt:       1          1         1.70000E-05
+    vcs_TP:           1          3         2.07000E-04
+    vcs_inest:        0                    0.00000E+00
+    vcs_TotalTime:                         6.38000E-04

  Results from vcs:

<<<
FAILED
* Running test 'VCS-LiSi-verbose'...
Comparing 'verbose_blessed.txt' with 'verbose_output.txt'
Values differ:         101325         625.15; rel. err = 1.975e+00; abs. err = 1.007e+05
Values differ:         2475.9    -7.3846e+06; rel. err = 2.001e+00; abs. err = 7.387e+06
Values differ:    -8.9323e+06         2475.9; rel. err = 2.001e+00; abs. err = 8.935e+06
Values differ:         1331.6    -8.9323e+06; rel. err = 2.001e+00; abs. err = 8.934e+06
Values differ:         1171.8         1331.6; rel. err = 1.277e-01; abs. err = 1.598e+02
Values differ:            0.3            0.7; rel. err = 8.000e-01; abs. err = 4.000e-01
Values differ:         101325         625.15; rel. err = 1.975e+00; abs. err = 1.007e+05
Values differ:    -2.5009e+06    -2.5006e+06; rel. err = 1.200e-04; abs. err = 3.000e+02
Values differ:           6116    -2.5009e+06; rel. err = 2.010e+00; abs. err = 2.507e+06
Values differ:     -6.324e+06           6116; rel. err = 2.004e+00; abs. err = 6.330e+06
Values differ:         4196.8     -6.324e+06; rel. err = 2.003e+00; abs. err = 6.328e+06
Values differ:            0.5    1.39772e-13; rel. err = 2.000e+00; abs. err = 5.000e-01
Values differ:         101325         625.15; rel. err = 1.975e+00; abs. err = 1.007e+05
Values differ:    -1.2398e+14    -2.3852e+07; rel. err = 2.000e+00; abs. err = 1.240e+14
Values differ:              0    -1.2398e+14; rel. err = 2.000e+00; abs. err = 1.240e+14
Values differ:    -2.3852e+07              0; rel. err = 2.000e+00; abs. err = 2.385e+07
Values differ:              0    -2.3852e+07; rel. err = 2.000e+00; abs. err = 2.385e+07
Found differences between /home/sagitter/rpmbuild/BUILD/cantera-d4ddabc76c2bdfd54d61f76de6bfe477912325eb/test_problems/VCSnonideal/LatticeSolid_LiSi/verbose_blessed.txt and /home/sagitter/rpmbuild/BUILD/cantera-d4ddabc76c2bdfd54d61f76de6bfe477912325eb/test_problems/VCSnonideal/LatticeSolid_LiSi/verbose_output.txt:
>>>
--- 

+++ 

@@ -449,16 +449,16 @@



 Counters:         Iterations          Time (seconds)
-    vcs_basopt:       1                 NA
-    vcs_TP:           3                 NA
+    vcs_basopt:       1             1.36000E-04
+    vcs_TP:           3             1.06900E-03
 --------------------------------------------------------------------------------
 --------------------------------------------------------------------------------

 TCounters:   Num_Calls   Total_Its       Total_Time (seconds)
-    vcs_basopt:       1          1             NA
-    vcs_TP:           1          3             NA
-    vcs_inest:        0                        NA
-    vcs_TotalTime:                             NA
+    vcs_basopt:       1          1         1.36000E-04
+    vcs_TP:           1          3         1.06900E-03
+    vcs_inest:        0                    0.00000E+00
+    vcs_TotalTime:                         1.62300E-03

  Results from vcs:

@@ -475,11 +475,12 @@

 V(i)                5.000e-01         5.000e-01       -3.513e+06
 LiFixed             1.000e+02         1.000e+00       -1.656e+08
 -------------------------------------------------------------
-VCS solver succeeded
+Total time = 1.845000e-03 seconds
+*************** MoltenSalt_electrolyte *****************
 *************** MoltenSalt_electrolyte *****************
 Moles: 10
-
   MoltenSalt_electrolyte:
+

        temperature          625.15  K
           pressure          101325  Pa
@@ -488,14 +489,14 @@


                           1 kg            1 kmol
                        -----------      ------------
-          enthalpy     -7.3846e+06       -3.843e+08     J
+   internal energy     -7.3846e+06       -3.843e+08     J
    internal energy     -7.3846e+06       -3.843e+08     J
            entropy          2475.9        1.288e+05     J/K
     Gibbs function     -8.9323e+06       -4.648e+08     J
  heat capacity c_p          1331.6         6.93e+04     J/K
  heat capacity c_v          1171.8        6.098e+04     J/K
-
                            X                 Y          Chem. Pot. / RT
+                     -------------     ------------     ------------
                      -------------     ------------     ------------
            LiCl(L)            0.7         0.570236         -86.6013
             KCl(L)            0.3         0.429764         -96.0362
@@ -516,19 +517,19 @@

    internal energy     -2.5009e+06       -1.661e+08     J
            entropy            6116        4.062e+05     J/K
     Gibbs function      -6.324e+06       -4.201e+08     J
- heat capacity c_p          4196.8        2.788e+05     J/K
  heat capacity c_v          4196.8        2.788e+05     J/K
-
+ heat capacity c_v          4196.8        2.788e+05     J/K
                            X                 Y          Chem. Pot. / RT
+                     -------------     ------------     ------------
                      -------------     ------------     ------------
          Li7Si3(S)            0.5                1         -80.8307
              Li(i)    1.39772e-13       1.4606e-14         -31.8338
               V(i)            0.5      7.52765e-23        0.0172766
-
+*************** LiFixed *****************
 *************** LiFixed *****************
 Moles: 100.005
-
   LiFixed:
+

        temperature          625.15  K
           pressure          101325  Pa
@@ -541,11 +542,11 @@

    internal energy     -1.2398e+14       -8.605e+14     J
            entropy               0                0     J/K
     Gibbs function     -2.3852e+07       -1.656e+08     J
- heat capacity c_p               0                0     J/K
  heat capacity c_v               0                0     J/K
-
+ heat capacity c_v               0                0     J/K
                            X                 Y          Chem. Pot. / RT
                      -------------     ------------     ------------
+                     -------------     ------------     ------------
            LiFixed              1                1         -31.8511


<<<
FAILED
g++ -o test_problems/VPsilane_test/silane_equil.o -c -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic --std=c++14 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -pthread -DNDEBUG -DNDEBUG -Iinclude -Isrc -Itest_problems/shared -I/usr/include/eigen3 -I/usr/include test_problems/VPsilane_test/silane_equil.cpp
g++ -o test_problems/VPsilane_test/VPsilane_test -pthread -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld test_problems/VPsilane_test/silane_equil.o -Lbuild/lib -lcantera -lsundials_cvodes -lsundials_ida -lsundials_nvecserial -lfmt
* Running test 'VPsilane_test'...
Comparing 'output_blessed.txt' with 'output_output.txt'
PASSED
printReport(["test_results"], [])

*****************************
***    Testing Summary    ***
*****************************

Tests passed: 1113
Up-to-date tests skipped: 0
Tests failed: 3
Failed tests:
    - VCS-LiSi
    - VCS-NaCl
    - VCS-LiSi-verbose

*****************************
scons: *** [test_results] One or more tests failed.
```

**Comment by speth** [comment]
What commit do you have checked out? I was running into exactly this problem before, but this should be fixed by 62524e8. The latest on the branch with all of the Fedora-related fixes is 1c86b81.

**Comment by sagitter** [comment]
d4ddabc76c2bdfd54d61f76de6bfe477912325eb + patches.

**Comment by speth** [comment]
Then you're behind. Please update to 1c86b81.

**Comment by speth** [comment]
@sagitter Can you confirm that this issue is resolved for you?

**Comment by sagitter** [comment]
This specific issue is resolved.
I noted other failures on `ix86` arch only:

```
Tests passed: 1111
Up-to-date tests skipped: 0
Tests failed: 5
Failed tests:
    - python3:test_thermo.TestSpeciesThermo.test_create
    - python2:test_thermo.TestSpeciesThermo.test_create
    - general: Polyfit.exact_fit
    - python3:test_thermo.TestSpeciesThermo.test_wrap
    - python2:test_thermo.TestSpeciesThermo.test_wrap
*****************************
scons: *** [test_results] One or more tests failed.
```

Full log: https://copr-be.cloud.fedoraproject.org/results/sagitter/petsc/fedora-rawhide-i386/00375546-cantera/build.log.gz

**Comment by speth** [comment]
Does 791c9d1599f7 resolve these test failures?

**Comment by sagitter** [comment]
Just the `Polyfit.exact_fit` one; `test_thermo.TestSpeciesThermo.test_wrap` are still failing (on `ix86` architectures only): https://copr-be.cloud.fedoraproject.org/results/sagitter/petsc/fedora-rawhide-i386/00421554-cantera/build.log.gz

**Comment by speth** [comment]
Those test failures don't seem to correspond to either the current `master` branch or `791c9d1`:

```
======================================================================
FAIL: test_create (cantera.test.test_thermo.TestSpeciesThermo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/cantera-1c86b8168728de6e356ec6cbe9350d9cb4494655/build/python3/cantera/test/test_thermo.py", line 954, in test_create
    self.assertAlmostEqual(st.h(T), self.gas.enthalpy_mole)
AssertionError: -207300880.89767623 != -207300880.8976763 within 7 places
======================================================================
FAIL: test_wrap (cantera.test.test_thermo.TestSpeciesThermo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/cantera-1c86b8168728de6e356ec6cbe9350d9cb4494655/build/python3/cantera/test/test_thermo.py", line 971, in test_wrap
    self.assertAlmostEqual(st.h(T), self.gas.enthalpy_mole)
AssertionError: -207300880.89767623 != -207300880.8976763 within 7 places
----------------------------------------------------------------------
```

The lines triggering the assertions don't match up with the lines in `test_thermo.py`. And in the updated commit, `test_thermo.py` never even calls `assertAlmostEqual`. So I really don't know what's happening with your build system, or how you got the update that fixes the `Polyfit.exact_fit` test but not the other changes.

**Comment by sagitter** [comment]
I have applied the https://github.com/Cantera/cantera/commit/791c9d1599f7c578e63dcdce0f825467783307f9 changes as patch.

I'm rebuilding with latest source code.

**Comment by speth** [comment]
I meant the branch of which 791c9d1 is the tip, not just that one commit. 791c9d1 is a one-line change that clearly only affects the `Polyfit.exact_fit` test. 

More generally, I don't think it's productive for me to work on fixing things on some unpublished fork of yours where you're cherry-picking a handful of changes. Please use the current master branch as the reference point for any bug reports.

**Comment by sagitter** [comment]
> I meant the branch of which 791c9d1 is the tip

Rebuild successfully, all tests passed.

> Please use the current master branch as the reference point for any bug reports.

Okay.
